### PR TITLE
Support building Raspbian buildroot

### PR DESCRIPTION
**Pull request by JedMeister**
Additions/adjustments to support Raspbian buildroot

Also a minor adjustment to README

### CODE REVIEW

**Comment by alonswartz** [comment]
Merged. Note that it would have been better to issue 2 separate pull requests as they are unrelated:
1. added raspbian as supported distro
2. updated readme for autoversion location

**Comment by JedMeister** [comment]
Thanks Alon. 

So for future reference: to clarify; I should have done the README update in a separate branch!? And then made a separate pull request...

**Comment by alonswartz** [comment]
Yep... 

We should consider tweaking the gitflow docs to clarify.
https://github.com/turnkeylinux/tracker/blob/master/GITFLOW.rst

```
When working on something new, whether it be a bugfix or new feature,
create a descriptively named branch off of master.
```

**Comment by JedMeister** [comment]
I've had a go at improving that: https://github.com/turnkeylinux/tracker/pull/316

**Pull request merged**
